---
abstract: 'perlrdf command line utils'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0
  Test::More: 0.61
  Test::RDF: 1.00
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::perlrdf
name: App-perlrdf
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0
  App::Cmd: 0
  App::Cmd::Plugin::Prompt: 0
  Data::UUID: 0
  JSON: 2.00
  LWP::UserAgent: 0
  Object::AUTHORITY: 0
  Path::Class: 0
  PerlX::Maybe: 0
  RDF::NS: 0
  RDF::TriN3: 0
  RDF::Trine: 0
  RDF::TrineX::Functions: 0.004
  RDF::TrineX::Parser::Pretdsl: 0
  RDF::TrineX::Parser::RDFa: 0
  URI: 0
  URI::file: 0
  namespace::clean: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=App-perlrdf
  homepage: https://metacpan.org/release/App-perlrdf
  license: http://dev.perl.org/licenses/
version: 0.001
